# feature selection
select_k_best: 10

#mlp
hidden_layer_sizes: 100
hidden_layer_activation: relu
optimizer: adam
l2: 0.01
batch_size: 16
learning_rate: adaptive
learning_rate_init: 0.01
EPOCHS: 10
tol: 1e-4
early_stopping: True
n_iter_no_change: 10

#lof
n_neighbours: 20
lof_algo: ball_tree

#isolation forest
n_estimators_isolation: 100
bootstrap: False

#dbscan
eps: 0.5
min_samples: 5

#custom_bagging
estimator: DecisionTreeClassifier
n_estimators_bagging: 10
max_samples: 1.0
max_features: 1.0
bootstrap_bagging: False


#xgboost
n_estimators_xgboost: 5
max_depth_xgboost: 3
learning_rate_xgboost: 1

#random forest
n_estimators_random_forest: 100
max_depth_random_forest: 100
criterion: gini
bootstrap_random_forest: False

#logistic regression
penalty: elasticnet
solver: saga
max_iter_logreg: 100
l1_ratio: 0.5
