# feature selection
select_k_best: 15

#mlp
hidden_layer_sizes: 200
hidden_layer_activation: relu
optimizer: adam
l2: 0.01
batch_size: 16
learning_rate: adaptive
learning_rate_init: 0.01
EPOCHS: 500
tol: 00.0001
early_stopping: True
n_iter_no_change: 10

#isolation forest
n_estimators_isolation: 200
bootstrap: False

#xgboost
n_estimators_xgboost: 20
max_depth_xgboost: 20
learning_rate_xgboost: 1

#random forest
n_estimators_random_forest: 400
max_depth_random_forest: 400
criterion: gini
bootstrap_random_forest: False

#logistic regression
penalty: elasticnet
solver: saga
max_iter_logreg: 200
l1_ratio: 0.5

#mlflow
MLFLOW_TRACKING_URI: https://dagshub.com/sanskarmodi8/network_intrusion_detection.mlflow