artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://drive.google.com/file/d/17BeRl9XUdTLx1QpW7HdxkIXlUb-STLkQ/view?usp=sharing
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion

eda_and_feature_engineering:
  root_dir: artifacts/eda_and_feature_engineering
  data_file: artifacts/data_ingestion/US-AirForce-LAN-Network-Intrusion/data/data.csv
  final_data_train: artifacts/eda_and_feature_engineering/final_data_train.csv
  final_data_test: artifacts/eda_and_feature_engineering/final_data_test.csv


prepare_model:
  root_dir: artifacts/prepare_model
  isolation_forest_model_path: artifacts/prepare_model/isolation_forest_model.h5
  log_reg_model_path: artifacts/prepare_model/log_reg_model.h5
  decision_trees_model_path: artifacts/prepare_model/decision_trees_model.h5
  random_forest_model_path: artifacts/prepare_model/random_forest_model.h5
  xgboost_model_path: artifacts/prepare_model/xgboost_model.h5
  svm_model_path: artifacts/prepare_model/svm_model.h5
  naive_bayes_model_path: artifacts/prepare_model/naive_bayes_model.h5
  mlp_model_path: artifacts/prepare_model/mlp_model.h5
  

training:
  root_dir: artifacts/training
  train_data_path: artifacts/eda_and_feature_engineering/final_data_train.csv
  trained_isolation_forest_model_path: artifacts/training/isolation_forest_model_trained.h5
  trained_log_reg_model_path: artifacts/training/log_reg_model_trained.h5
  trained_decision_trees_model_path: artifacts/training/decision_trees_model_trained.h5
  trained_random_forest_model_path: artifacts/training/random_forest_model_trained.h5
  trained_xgboost_model_path: artifacts/training/xgboost_model_trained.h5
  trained_svm_model_path: artifacts/training/svm_model_trained.h5
  trained_naive_bayes_model_path: artifacts/training/naive_bayes_model_trained.h5
  trained_mlp_model_path: artifacts/training/mlp_model_trained.h5

evaluation:
  root_dir: artifacts/evaluation
  test_data_path: artifacts/eda_and_feature_engineering/final_data_test.csv
  trained_isolation_forest_model_path: artifacts/training/isolation_forest_model_trained.h5
  trained_log_reg_model_path: artifacts/training/log_reg_model_trained.h5
  trained_decision_trees_model_path: artifacts/training/decision_trees_model_trained.h5
  trained_random_forest_model_path: artifacts/training/random_forest_model_trained.h5
  trained_xgboost_model_path: artifacts/training/xgboost_model_trained.h5
  trained_svm_model_path: artifacts/training/svm_model_trained.h5
  trained_naive_bayes_model_path: artifacts/training/naive_bayes_model_trained.h5
  trained_mlp_model_path: artifacts/training/mlp_model_trained.h5
  best_model_dir: artifacts/evaluation/best_model
  best_model_path: artifacts/evaluation/best_model/best_model.h5
  best_model_name: artifacts/evaluation/best_model/name.txt